#!/bin/sh
# The fused engine's check matrix: the Elixir engine is the only engine, so
# the matrix is Elixir-native. The retired Lua suites, the nvim -l syntax
# pass and StyLua died with the Lua engine (tests/goldens/ stays canonical,
# regenerated by `mix workstation.goldens`).
set -eu
repo_root=$(CDPATH='' cd -P "$(dirname "$0")/../.." && pwd -P)
cd "$repo_root"
fail=0

step() { printf '\n== %s\n' "$1"; }

step 'engine suite (mix test)'
(cd elixir && mise exec -- mix test) || fail=1

step 'golden contract (byte-identical replay)'
if (cd elixir && mise exec -- mix workstation.goldens /tmp/workstation-goldens-check) \
	&& diff -r /tmp/workstation-goldens-check tests/goldens; then
	rm -rf /tmp/workstation-goldens-check
else
	fail=1
fi

step 'shell syntax (sh -n) and ShellCheck when available'
{
	find workstation .github/scripts -type f \( -name '*.sh' -o -name 'workstation' \) -print
	[ -f install.sh ] && printf '%s\n' install.sh
} | while IFS= read -r file; do
	sh -n "$file" || exit 1
	if command -v shellcheck >/dev/null 2>&1; then
		shellcheck -s sh "$file" || exit 1
	fi
done || fail=1
if ! command -v shellcheck >/dev/null 2>&1; then
	printf 'ShellCheck unavailable here; required in the Linux CI job.\n' >&2
fi

step 'release boot smoke (skipped when the local release build is cold)'
if [ -f elixir/workstation-0.1.0-linux-x64.tar.gz ]; then
	sh elixir/test/direct_boot.sh || fail=1
else
	printf 'no release tarball built; skipping (build with: cd elixir && mise exec -- env MIX_ENV=prod mix release workstation --overwrite)\n'
fi

step 'shim engine-repo anchor (non-bootstrap verb through the checkout shim)'
if [ -f elixir/workstation-0.1.0-linux-x64.tar.gz ]; then
	sh .github/scripts/shim-anchor.sh || fail=1
else
	printf 'no release tarball built; skipping (build with: cd elixir && mise exec -- env MIX_ENV=prod mix release workstation --overwrite)\n'
fi

step 'whitespace (git diff --check)'
git diff --check || fail=1

[ "$fail" -eq 0 ] || { printf '\ncheck.sh: FAILED\n' >&2; exit 1; }
printf '\ncheck.sh: OK\n'
