local commands = require("workstation.commands")
local leaf = require("packages.nvim.leaf")
local paths = require("workstation.paths")
local profile_module = require("packages.nvim.profile")
local provision = require("workstation.provision.recipes")

local module_path = debug.getinfo(1, "S").source:gsub("^@", "")
local package_root = vim.fs.dirname(vim.fs.normalize(module_path))

local function read_package_asset(relative)
	local file = assert(io.open(vim.fs.joinpath(package_root, relative), "rb"), "nvim asset missing: " .. relative)
	local contents = file:read("*a")
	file:close()
	return contents
end

-- The plugin lockfile is engine-seeded, runtime-extended mutable state:
-- Neovim records the active spec set into the deployed copy, which may
-- legitimately include host-provided specs (a followed desktop theme). The
-- committed asset stays the single source of engine pins; it is embedded
-- verbatim into the deploy-time merge program so the seed path is byte-stable.
local lazy_lock_pins = read_package_asset("files/.config/nvim/lazy-lock.json")
assert(type(vim.json.decode(lazy_lock_pins)) == "table", "lazy-lock.json asset is not a JSON object")

local PINS_MARKER = "__WORKSTATION_ENGINE_PINS__"
local lazy_lock_program_template = read_package_asset("files/modify/lazy-lock.json.sh")

local function replace_plain(subject, marker, replacement)
	local start = assert(subject:find(marker, 1, true), "lazy-lock merge template lost its marker")
	return subject:sub(1, start - 1) .. replacement .. subject:sub(start + #marker)
end

local lazy_lock_program = replace_plain(lazy_lock_program_template, PINS_MARKER, lazy_lock_pins)

-- nvim owns base editor state: config payload, lockfiles and the base/standard
-- and Go language intents of the composed profile. Language capabilities such
-- as typescript contribute their own intents and verify their own behavior.

local function read_json(path)
	local file = assert(io.open(path, "rb"))
	local contents = file:read("*a")
	file:close()
	return vim.json.decode(contents)
end

local function verify_locked_state(context)
	local first_line = vim.split(commands.capture(context.platform.nvim, { "--version" }), "\n")[1]
	assert(first_line == "NVIM v" .. context.versions.neovim, "Unexpected Neovim: " .. first_line)
	assert(
		vim.split(commands.capture("nvim", { "--version" }), "\n")[1] == first_line,
		"Configured environment does not resolve managed Neovim"
	)
	leaf.run_child(context, "messages", {})

	local config = context.paths.join(context.paths.home, ".config", "nvim")
	local lazy_root = context.paths.join(context.platform.nvim_data(), "lazy")
	-- Engine pins are asserted strictly: present in the deployed lockfile at
	-- the exact branch/commit AND installed at that commit.
	local engine_pins = assert(vim.json.decode(lazy_lock_pins), "lazy-lock asset lost its pins")
	local deployed_plugins = read_json(context.paths.join(config, "lazy-lock.json"))
	for name, pin in pairs(engine_pins) do
		local deployed = deployed_plugins[name]
		assert(
			type(deployed) == "table" and deployed.branch == pin.branch and deployed.commit == pin.commit,
			"lazy-lock.json is missing or diverged from the engine pin: " .. name
		)
		local head =
			vim.trim(commands.capture("git", { "-C", context.paths.join(lazy_root, name), "rev-parse", "HEAD" }))
		assert(head == pin.commit, "installed plugin is not at the engine pin: " .. name)
	end
	-- Host-provided extras are expected mutable state (for example a followed
	-- desktop-theme spec) and stay audit-only: they are reported, never failed.
	for name in pairs(deployed_plugins) do
		if engine_pins[name] == nil then
			local installed = context.paths.exists(context.paths.join(lazy_root, name))
			print(("nvim: lockfile extra%s: %s"):format(installed and "" or " (not installed)", name))
		end
	end
	for name in pairs(read_json(context.paths.join(config, "mason-lock.json"))) do
		assert(
			context.paths.exists(context.paths.join(context.platform.nvim_data(), "mason", "packages", name)),
			"Missing mason-lock.json entry: " .. name
		)
	end
end

-- nvim's deployed payload: base editor configuration and lockfiles. The
-- composed profile is generated by the nvim-profile compositor; language
-- plugin modules belong to their language capabilities. lazy-lock.json is
-- deliberately absent: it deploys through the merge program below instead of
-- a byte-owned whole-file recipe.
local payload = {
	".gitignore",
	"init.lua",
	"lazyvim.json",
	"mason-lock.json",
	"neoconf.json",
	"stylua.toml",
	"lua/config/autocmds.lua",
	"lua/config/keymaps.lua",
	"lua/config/lazy.lua",
	"lua/config/options.lua",
	"lua/config/sync.lua",
	"lua/plugins/debugging.lua",
	"lua/plugins/editor.lua",
	"lua/plugins/lsp.lua",
	"lua/plugins/mason-lock.lua",
	"lua/plugins/mason.lua",
	"lua/plugins/testing.lua",
	"lua/plugins/theme.lua",
	"lua/plugins/treesitter.lua",
	"lua/plugins/ui.lua",
}

-- nvim's own profile intents, in the composed order they declare: Go before
-- TypeScript (contributed by the typescript capability) before standard.
local intents = {
	{
		order = 10,
		entry = {
			id = "go",
			requires = { "go" },
			lazyvim_extras = { "lazyvim.plugins.extras.lang.go" },
			language_cases = {
				{
					language = "go",
					filename = "attachment_test.go",
					contents = "package behavior\n\nvar answer = 42\n",
					client = "gopls",
				},
			},
		},
	},
	{
		order = 30,
		entry = {
			id = "standard",
			lazyvim_extras = {
				"lazyvim.plugins.extras.lang.docker",
				"lazyvim.plugins.extras.lang.json",
				"lazyvim.plugins.extras.lang.markdown",
				"lazyvim.plugins.extras.lang.tailwind",
				"lazyvim.plugins.extras.lang.toml",
				"lazyvim.plugins.extras.lang.yaml",
			},
			language_cases = {
				{
					language = "lua",
					filename = "attachment-test.lua",
					contents = "local answer = 42\n",
					client = "lua_ls",
				},
				{
					language = "html",
					filename = "attachment-test.html",
					contents = "<!doctype html><title>test</title>\n",
					client = "html",
				},
				{
					language = "css",
					filename = "attachment-test.css",
					contents = "body { color: red; }\n",
					client = "cssls",
				},
				{
					language = "json",
					filename = "attachment-test.json",
					contents = '{ "answer": 42 }\n',
					client = "jsonls",
				},
				{ language = "yaml", filename = "attachment-test.yaml", contents = "answer: 42\n", client = "yamlls" },
				{
					language = "markdown",
					filename = "attachment-test.md",
					contents = "# Behavior test\n",
					client = "marksman",
				},
				{ language = "dockerfile", filename = "Dockerfile", contents = "FROM scratch\n", client = "dockerls" },
			},
		},
	},
}

return function(environment)
	local home = assert(
		assert(environment, "nvim package requires a factory environment").context,
		"nvim package requires a runtime context"
	).paths.home
	local contributes = {
		provision.chezmoi({
			target = ".local/bin/nvim",
			kind = "symlink",
			to = paths.join(home, ".local/opt/nvim/bin/nvim"),
		}),
		-- Engine-seeded, runtime-extended mutable target: modify programs are
		-- never byte-fingerprint-compared, so legitimate runtime rewrites (host
		-- specs recorded by lazy.nvim) reconcile at the next apply instead of
		-- failing closed. The program seeds the engine baseline verbatim.
		provision.chezmoi({
			target = ".config/nvim/lazy-lock.json",
			kind = "modify",
			executable = true,
			content = lazy_lock_program,
		}),
	}
	for _, name in ipairs(payload) do
		table.insert(
			contributes,
			provision.chezmoi({
				target = ".config/nvim/" .. name,
				kind = "file",
				asset = "files/.config/nvim/" .. name,
			})
		)
	end
	for _, intent in ipairs(intents) do
		table.insert(contributes, profile_module.recipe({ order = intent.order, entry = intent.entry }))
	end
	return {
		id = "nvim",
		requires = { "foundation", "node", "go" },
		contributes = contributes,
		sync = function(context)
			assert(context.nvim_profile, "nvim sync requires a composed profile")
			for _, operation in ipairs({
				{ "Restoring Neovim plugins", "lazy-restore" },
				{ "Removing inactive Neovim plugins", "lazy-clean" },
				{ "Restoring Mason packages", "mason" },
				{ "Updating Tree-sitter parsers", "treesitter" },
			}) do
				print("\n  -> " .. operation[1])
				leaf.run_child(context, "sync", { operation = operation[2] }, true)
			end
		end,
		verify = function(context)
			-- The composed profile is source-derived: a tampered deployed copy
			-- cannot alter what is verified here.
			local profile = assert(context.nvim_profile, "nvim verify requires a composed profile")
			verify_locked_state(context)
			for _, contribution in ipairs(profile) do
				leaf.verify_mason(context, contribution)
			end
			for _, intent in ipairs(intents) do
				if intent.entry.plugin_module then
					leaf.verify_module(context, intent.entry.plugin_module)
				end
				leaf.verify_cases(context, intent.entry)
			end
		end,
	}
end
