local commands = require("workstation.commands")
local leaf = require("packages.nvim.leaf")
local paths = require("workstation.paths")
local profile_module = require("packages.nvim.profile")
local provision = require("workstation.provision.recipes")

-- nvim owns base editor state: config payload, lockfiles and the base/standard
-- and Go language intents of the composed profile. Language capabilities such
-- as typescript contribute their own intents and verify their own behavior.

local function read_json(path)
	local file = assert(io.open(path, "rb"))
	local contents = file:read("*a")
	file:close()
	return vim.json.decode(contents)
end

local function verify_locked_state(context)
	local first_line = vim.split(commands.capture(context.platform.nvim, { "--version" }), "\n")[1]
	assert(first_line == "NVIM v" .. context.versions.neovim, "Unexpected Neovim: " .. first_line)
	assert(
		vim.split(commands.capture("nvim", { "--version" }), "\n")[1] == first_line,
		"Configured environment does not resolve managed Neovim"
	)
	leaf.run_child(context, "messages", {})

	local config = context.paths.join(context.paths.home, ".config", "nvim")
	for _, lock in ipairs({
		{ "lazy-lock.json", context.paths.join(context.platform.nvim_data(), "lazy") },
		{ "mason-lock.json", context.paths.join(context.platform.nvim_data(), "mason", "packages") },
	}) do
		for name in pairs(read_json(context.paths.join(config, lock[1]))) do
			assert(context.paths.exists(context.paths.join(lock[2], name)), "Missing " .. lock[1] .. " entry: " .. name)
		end
	end
end

-- nvim's deployed payload: base editor configuration and lockfiles. The
-- composed profile is generated by the nvim-profile compositor; language
-- plugin modules belong to their language capabilities.
local payload = {
	".gitignore",
	"init.lua",
	"lazy-lock.json",
	"lazyvim.json",
	"mason-lock.json",
	"neoconf.json",
	"stylua.toml",
	"lua/config/autocmds.lua",
	"lua/config/keymaps.lua",
	"lua/config/lazy.lua",
	"lua/config/options.lua",
	"lua/config/sync.lua",
	"lua/plugins/debugging.lua",
	"lua/plugins/editor.lua",
	"lua/plugins/lsp.lua",
	"lua/plugins/mason-lock.lua",
	"lua/plugins/mason.lua",
	"lua/plugins/testing.lua",
	"lua/plugins/theme.lua",
	"lua/plugins/treesitter.lua",
	"lua/plugins/ui.lua",
}

-- nvim's own profile intents, in the composed order they declare: Go before
-- TypeScript (contributed by the typescript capability) before standard.
local intents = {
	{
		order = 10,
		entry = {
			id = "go",
			requires = { "go" },
			lazyvim_extras = { "lazyvim.plugins.extras.lang.go" },
			language_cases = {
				{
					language = "go",
					filename = "attachment_test.go",
					contents = "package behavior\n\nvar answer = 42\n",
					client = "gopls",
				},
			},
		},
	},
	{
		order = 30,
		entry = {
			id = "standard",
			lazyvim_extras = {
				"lazyvim.plugins.extras.lang.docker",
				"lazyvim.plugins.extras.lang.json",
				"lazyvim.plugins.extras.lang.markdown",
				"lazyvim.plugins.extras.lang.tailwind",
				"lazyvim.plugins.extras.lang.toml",
				"lazyvim.plugins.extras.lang.yaml",
			},
			language_cases = {
				{
					language = "lua",
					filename = "attachment-test.lua",
					contents = "local answer = 42\n",
					client = "lua_ls",
				},
				{
					language = "html",
					filename = "attachment-test.html",
					contents = "<!doctype html><title>test</title>\n",
					client = "html",
				},
				{
					language = "css",
					filename = "attachment-test.css",
					contents = "body { color: red; }\n",
					client = "cssls",
				},
				{
					language = "json",
					filename = "attachment-test.json",
					contents = '{ "answer": 42 }\n',
					client = "jsonls",
				},
				{ language = "yaml", filename = "attachment-test.yaml", contents = "answer: 42\n", client = "yamlls" },
				{
					language = "markdown",
					filename = "attachment-test.md",
					contents = "# Behavior test\n",
					client = "marksman",
				},
				{ language = "dockerfile", filename = "Dockerfile", contents = "FROM scratch\n", client = "dockerls" },
			},
		},
	},
}

return function(environment)
	local home = assert(
		assert(environment, "nvim package requires a factory environment").context,
		"nvim package requires a runtime context"
	).paths.home
	local contributes = {
		provision.chezmoi({
			target = ".local/bin/nvim",
			kind = "symlink",
			to = paths.join(home, ".local/opt/nvim/bin/nvim"),
		}),
	}
	for _, name in ipairs(payload) do
		table.insert(
			contributes,
			provision.chezmoi({
				target = ".config/nvim/" .. name,
				kind = "file",
				asset = "files/.config/nvim/" .. name,
			})
		)
	end
	for _, intent in ipairs(intents) do
		table.insert(contributes, profile_module.recipe({ order = intent.order, entry = intent.entry }))
	end
	return {
		id = "nvim",
		requires = { "foundation", "node", "go" },
		contributes = contributes,
		sync = function(context)
			assert(context.nvim_profile, "nvim sync requires a composed profile")
			for _, operation in ipairs({
				{ "Restoring Neovim plugins", "lazy-restore" },
				{ "Removing inactive Neovim plugins", "lazy-clean" },
				{ "Restoring Mason packages", "mason" },
				{ "Updating Tree-sitter parsers", "treesitter" },
			}) do
				print("\n  -> " .. operation[1])
				leaf.run_child(context, "sync", { operation = operation[2] }, true)
			end
		end,
		verify = function(context)
			-- The composed profile is source-derived: a tampered deployed copy
			-- cannot alter what is verified here.
			local profile = assert(context.nvim_profile, "nvim verify requires a composed profile")
			verify_locked_state(context)
			for _, contribution in ipairs(profile) do
				leaf.verify_mason(context, contribution)
			end
			for _, intent in ipairs(intents) do
				if intent.entry.plugin_module then
					leaf.verify_module(context, intent.entry.plugin_module)
				end
				leaf.verify_cases(context, intent.entry)
			end
		end,
	}
end
