project_name: "Workstation"
default_status: "To Do"
statuses: ["To Do", "In Progress", "Done"]
labels: []
definition_of_done: ["Test end to end local node communication and cross node communication (if available), synced on at least machines when remoting is available"]
date_format: yyyy-mm-dd
max_column_width: 20
default_editor: "nvim"
auto_open_browser: false
default_port: 6420
remote_operations: true
auto_commit: true
filesystem_only: false
zero_padded_ids: 3
bypass_git_hooks: true
check_active_branches: true
active_branch_days: 15
task_prefix: "task"
