import test from "node:test";
import assert from "node:assert/strict";
import { publicAgentView, registerClientHandlers } from "../../home/dot_pi/private_agent/extensions/actor-client/handlers.ts";
import { ActorClientConversationLog, ActorClientLifecycleConversation, actorClientPendingStatus } from "../../home/dot_pi/private_agent/extensions/actor-client/index.ts";
import { outgoingExchange, renderCommunicationCard } from "../../home/dot_pi/private_agent/extensions/hosted-pi-bridge/communication-ui.ts";
const toolsafeRender = (view, theme) => renderCommunicationCard(view, theme).render(80).join("\n");

test("actor-client public views use display metadata and suppress raw runtime internals", () => {
  const view = publicAgentView({agentId:"agent-42",displayName:"Release Reviewer",role:"Review Lead",hostedPiRuntime:{state:3,bridgeReady:true,cleanupPending:false,runtimeId:"raw-runtime",tmuxSessionId:"$1",tmuxSession:"raw",panePid:123,piSessionName:"hosted-raw"}});
  assert.deepEqual(view,{agentId:"agent-42",displayName:"Release Reviewer",role:"Review Lead",state:3,bridgeReady:true,cleanupPending:false});
  const encoded = JSON.stringify(view);
  for (const forbidden of ["raw-runtime","tmux","panePid","123","hosted-raw","attachTarget","sessionId","handle","fence"]) assert.doesNotMatch(encoded,new RegExp(forbidden,"i"));
});

test("actor-client pending lifecycle status uses authoritative display name", () => {
  assert.equal(actorClientPendingStatus({ displayName: "Code Reviewer" }), "◌ Waiting for Code Reviewer…");
  assert.doesNotMatch(actorClientPendingStatus({ displayName: "Code Reviewer" }), /actor42|agentId|raw|Waiting for actor/);
});

test("actor-client lifecycle conversation publishes one coherent final exchange across status, wait, and replay", () => {
  const appended=[];
  const log = new ActorClientConversationLog({ appendEntry: (customType, data) => appended.push({ customType, data }) });
  const lifecycle = new ActorClientLifecycleConversation(log);
  lifecycle.remember("life", "review behavior");
  const pendingStart = outgoingExchange({ key: "actor-client:lifecycle:life", target: "Release Reviewer", body: lifecycle.body("life"), accepted: true, completed: false, mode: "ask" });
  const pendingStatus = outgoingExchange({ key: "actor-client:lifecycle:life", target: "Release Reviewer", body: lifecycle.body("life"), accepted: true, completed: false, mode: "ask" });
  const finalWait = outgoingExchange({ key: "actor-client:lifecycle:life", target: "Release Reviewer", body: lifecycle.body("life"), reply: "done", accepted: true, completed: true, mode: "ask" });
  assert.equal(lifecycle.publish(pendingStart, false), false);
  assert.equal(lifecycle.publish(pendingStatus, false), false);
  assert.equal(appended.length, 0, "nonterminal lifecycle updates must use realtime status, not visible cards");
  assert.equal(lifecycle.publish(finalWait, true), true);
  assert.equal(appended.length, 1);
  assert.equal(appended[0].data.view.body, "review behavior");
  assert.equal(appended[0].data.view.reply, "done");
  const theme={fg:(_name,text)=>text,bg:(_name,text)=>text,bold:(text)=>text};
  const visible=toolsafeRender(appended[0].data.view, theme);
  assert.doesNotMatch(visible, /life|lifecycleId/);
  assert.equal(lifecycle.publish(finalWait, true), false, "terminal replay emitted a duplicate lifecycle card");
  const restored = new ActorClientConversationLog({ appendEntry: (customType, data) => appended.push({ customType, data }) });
  restored.restore(appended.map((entry) => ({ type: "custom", customType: entry.customType, data: entry.data })));
  const restoredLifecycle = new ActorClientLifecycleConversation(restored);
  assert.equal(restoredLifecycle.publish(finalWait, true), false, "reconnect restore emitted a duplicate lifecycle card");
  assert.equal(appended.length, 1);
});

test("regular client Pi callbacks register noncolliding commands and tools", async () => {
  const commands=new Map(),tools=new Map(),calls=[];
  const api={registerCommand:(name,value)=>commands.set(name,value),registerTool:(value)=>tools.set(value.name,value)};
  const operations={create:async(a,p,d,r)=>(calls.push(["create",a,p,d,r]),{a,p,d,r}),list:async()=>(calls.push(["list"]),["a","b"]),send:async(a,p)=>(calls.push(["send",a,p]),{accepted:true,completed:true,target:"Release Reviewer",kind:"Tell",requestId:"request-send",dedupeId:"dedupe-send",chainId:"chain-send",sourceMutationSequence:"1",communicationView:outgoingExchange({key:"request-send",target:"Release Reviewer",body:p,accepted:true,completed:true,mode:"tell"})}),ask:async(a,p)=>(calls.push(["ask",a,p]),{accepted:true,completed:true,answer:"done",target:"Release Reviewer",kind:"Ask",requestId:"request-ask",dedupeId:"dedupe-ask",chainId:"chain-ask",sourceMutationSequence:"2",communicationView:outgoingExchange({key:"request-ask",target:"Release Reviewer",body:p,reply:"done",accepted:true,completed:true,mode:"ask"})}),promptStart:async(a,p)=>(calls.push(["promptStart",a,p]),{lifecycleId:"life",requestId:"request-life",dedupeId:"dedupe-life",chainId:"chain-life",sourceMutationSequence:"3",sourceStableId:"project-manager",sourceDisplayName:"Project Manager",sourceRole:"project manager",targetStableId:"actor42",targetDisplayName:"Release Reviewer",targetRole:"review lead",state:1,terminal:false}),promptStatus:async(a,l,w)=>(calls.push(["promptStatus",a,l,w]),{lifecycleId:l,state:2,terminal:false}),promptWait:async(a,l,w)=>(calls.push(["promptWait",a,l,w]),{lifecycleId:l,state:3,terminal:false}),status:async(a)=>(calls.push(["status",a]),{}),attach:async(a)=>(calls.push(["attach",a]),"tmux"),stop:async(a)=>(calls.push(["stop",a]),{}),subscribe:async(a)=>(calls.push(["subscribe",a]),{})};
  registerClientHandlers(api,operations,{empty:{},target:{},task:{},lifecycle:{},create:{}});
  assert.deepEqual([...commands.keys()],["actor-client-create","actor-client-list","actor-client-send","actor-client-ask","actor-client-prompt-start","actor-client-prompt-status","actor-client-prompt-wait","actor-client-status","actor-client-attach","actor-client-stop"]);
  assert.deepEqual([...tools.keys()],["actor_client_create","actor_client_list","actor_client_send","actor_client_ask","actor_client_prompt_start","actor_client_prompt_status","actor_client_prompt_wait","actor_client_status","actor_client_attach","actor_client_stop","actor_client_subscribe"]);
  const notices=[];
  const ctx={ui:{notify(message){notices.push(message);}}};
  const theme={fg:(_name,text)=>text,bg:(_name,text)=>text,bold:(text)=>text};
  await commands.get("actor-client-create").handler("actor42 -- /tmp/worktree -- Release Reviewer -- Review Lead",ctx);
  const noticesAfterCreate=notices.length;
  await commands.get("actor-client-send").handler("actor42 -- notification",ctx);
  await commands.get("actor-client-ask").handler("actor42 -- implement the task",ctx);
  assert.equal(notices.length,noticesAfterCreate,"message commands must render conversation entries, not popups");
  assert.equal(typeof tools.get("actor_client_ask").renderCall,"function");
  assert.equal(typeof tools.get("actor_client_ask").renderResult,"function");
  const askResult = await tools.get("actor_client_ask").execute("id",{agentId:"actor42",prompt:"next task"});
  assert.doesNotMatch(askResult.content[0].text,/^\s*[\[{]/,"tool content exposed raw JSON");
  assert.match(askResult.content[0].text,/requestId=request-ask/);
  assert.match(askResult.content[0].text,/dedupeId=dedupe-ask/);
  const sendResult = await tools.get("actor_client_send").execute("id",{agentId:"actor42",prompt:"tool tell"});
  const renderedSend = tools.get("actor_client_send").renderResult({details:sendResult.details},{},theme,{}).render(80).join("\n");
  assert.match(renderedSend,/✓ delivered/);
  const expandedSend = tools.get("actor_client_send").renderResult({details:sendResult.details},{expanded:true},theme,{}).render(80).join("\n");
  assert.match(expandedSend,/↑ Sent to Release Reviewer/);
  assert.match(expandedSend,/tool tell/);
  assert.doesNotMatch(renderedSend,/request-send|dedupe-send|chain-send|sourceMutationSequence/);
  assert.ok(notices.every((notice)=>!/^\s*[\[{]/.test(notice)),"command notification exposed raw JSON");
  const promptStart = await tools.get("actor_client_prompt_start").execute("id",{agentId:"actor42",prompt:"observed"});
  assert.match(promptStart.content[0].text,/lifecycleId=life/);
  assert.match(promptStart.content[0].text,/channel=actor-client-lifecycle/);
  assert.match(promptStart.content[0].text,/threadId=life/);
  assert.match(promptStart.content[0].text,/requestId=request-life/);
  assert.match(promptStart.content[0].text,/dedupeId=dedupe-life/);
  assert.match(promptStart.content[0].text,/sourceStableId=project-manager/);
  assert.match(promptStart.content[0].text,/sourceDisplayName=Project Manager/);
  assert.match(promptStart.content[0].text,/sourceRole=project manager/);
  assert.match(promptStart.content[0].text,/targetStableId=actor42/);
  assert.match(promptStart.content[0].text,/targetDisplayName=Release Reviewer/);
  assert.match(promptStart.content[0].text,/targetRole=review lead/);
  assert.match(promptStart.content[0].text,/terminal=false/);
  assert.match(promptStart.content[0].text,/next=actor_client_prompt_wait/);
  const humanStart=tools.get("actor_client_prompt_start").renderResult({details:promptStart.details},{},theme,{}).render(80).join("\n");
  assert.match(humanStart,/Started; waiting may continue later/);
  assert.doesNotMatch(humanStart,/life|lifecycleId|raw-[a-z]/);
  const promptWait = await tools.get("actor_client_prompt_wait").execute("id",{agentId:"actor42",lifecycleId:"life",waitMillis:10});
  assert.match(promptWait.content[0].text,/lifecycleId=life/);
  assert.match(promptWait.content[0].text,/channel=actor-client-lifecycle/);
  assert.match(promptWait.content[0].text,/threadId=life/);
  assert.match(promptWait.content[0].text,/state=3/);
  assert.doesNotMatch(promptWait.content[0].text,/^\s*[\[{]/);
  await tools.get("actor_client_subscribe").execute("id",{agentId:"actor42"});
  assert.deepEqual(calls,[ ["create","actor42","/tmp/worktree","Release Reviewer","Review Lead"], ["send","actor42","notification"], ["ask","actor42","implement the task"], ["ask","actor42","next task"], ["send","actor42","tool tell"], ["promptStart","actor42","observed"], ["promptWait","actor42","life",10], ["subscribe","actor42"] ]);
});
